name: legacy_tree_grid
description: "Display, filter, sort, select, and edit tabular data in a tree grid."
version: 0.2.1
repository: https://github.com/barneysspeedshop/legacy_tree_grid
screenshots: https://raw.githubusercontent.com/barneysspeedshop/legacy_tree_grid/refs/heads/main/assets/screenshot.png

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  legacy_context_menu: ^2.1.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
