name: legacy_tree_grid
description: "Display, filter, sort, select, and edit tabular data in a tree grid."
version: 0.6.0
repository: https://github.com/barneysspeedshop/legacy_tree_grid
screenshots:
  - description: "A screenshot of the legacy_tree_grid in action."
    path: assets/screenshot.png

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  legacy_context_menu: ^2.1.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
